/*
cat *.[hc] | grep -o '^\s*gl[A-Z][a-zA-Z0-9_]*' | awk '{print $1}' | sort -u | xargs -I {} echo "#define {}(...)"
* */

#ifdef PERF_TEST

/* just reset, don't draw actually */
#undef FLUSH_BUFFER
#define FLUSH_BUFFER() do {                                                    \
    if(vertexCounter) {                                                        \
        vertexCounter = 0;                                                     \
    }                                                                          \
} while(0)

#define glActiveTexture_(...)
#define glAlphaFunc(...)
#define glAttachObject_(...)
#define glBegin(...)
#define glBindAttribLocation_(...)
#define glBindBuffer_(...)
#define glBindFramebuffer_(...)
#define glBindRenderbuffer_(...)
#define glBindTexture(...)
#define glBlendEquation_(...)
#define glBlendFunc(...)
#define glBufferData_(...)
#define glBufferSubData_(...)
#define glCallList(...)
#define glCheckFramebufferStatus_(...) 1
#define glClear(...)
#define glClearColor(...)
#define glClientActiveTexture_(...)
#define glColor4f(...)
#define glColor4ub(...)
#define glColorMask(...)
#define glCompileShader_(...)
#define glCreateProgramObject_(...) 0
#define glCreateShaderObject_(...) 0
#define glDeleteBuffers_(...)
#define glDeleteFramebuffers_(...)
#define glDeleteObject_(...)
#define glDeleteRenderbuffers_(...)
#define glDeleteTextures(...)
#define glDisable(...)
#define glDisableClientState(...)
#define glDrawArrays(...)
#define glEnable(...)
#define glEnableClientState(...)
#define glEnd(...)
#define glEndList(...)
#define glFinish(...)
#define glFramebufferRenderbuffer_(...)
#define glFramebufferTexture2D_(...)
#define glGenBuffers_(...)
#define glGenerateMipmap_(...)
#define glGenFramebuffers_(...)
#define glGenRenderbuffers_(...)
#define glGenTextures(...)
#define glGetActiveUniform_(...)
#define glGetBufferSubData_(...)
#define glGetInfoLog_(...)
#define glGetIntegerv(...)
#define glGetObjectParameteriv_(...)
#define glGetProgramiv_(...)
#define glGetShaderiv_(...)
#define glGetUniformLocation_(...) 0
#define glLinkProgram_(...)
#define glLoadIdentity(...)
#define glMapBuffer_(...)
#define glMatrixMode(...)
#define glMultiTexCoord2f_(...)
#define glMultiTexCoord3f_(...)
#define glMultiTexCoord4f_(...)
#define glNewList(...)
#define glOrtho(...)
#define glPointSize(...)
#define glPopMatrix(...)
#define glPushMatrix(...)
#define glReadBuffer(...)
#define glReadPixels(...)
#define glRenderbufferStorage_(...)
#define glRotated(...)
#define glScaled(...)
#define glScalef(...)
#define glScissor(...)
#define glShaderSource_(...)
#define glStencilFunc(...)
#define glStencilOp(...)
#define glTexCoordPointer(...)
#define glTexEnvi(...)
#define glTexImage2D(...)
#define glTexParameteri(...)
#define glTranslated(...)
#define glTranslatef(...)
#define glUniform1f_(...)
#define glUniform1fv_(...)
#define glUniform1i_(...)
#define glUniform2f_(...)
#define glUniform2fv_(...)
#define glUniform3f_(...)
#define glUniform3fv_(...)
#define glUniform4f_(...)
#define glUniform4fv_(...)
#define glUnmapBuffer_(...)
#define glUseProgramObject_(...)
#define glVertex2f(...)
#define glVertexPointer(...)
#define glViewport(...)


#endif
